// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_lb9MJ0j6fHG8in_WIgV_m59m1OlnMzQ',
    appId: '1:710171120768:web:cda76b9056f3a00f30c265',
    messagingSenderId: '710171120768',
    projectId: 'bis-firebase-test3626',
    authDomain: 'bis-firebase-test3626.firebaseapp.com',
    storageBucket: 'bis-firebase-test3626.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2o39Od_xmnvvDA4TNKrkg7JsF2uKjuAA',
    appId: '1:710171120768:android:9f69f674b44fcd6e30c265',
    messagingSenderId: '710171120768',
    projectId: 'bis-firebase-test3626',
    storageBucket: 'bis-firebase-test3626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9LFDWFplr2DXaRfVjohQGke8xa2bOfmY',
    appId: '1:710171120768:ios:af32f5885837b8cf30c265',
    messagingSenderId: '710171120768',
    projectId: 'bis-firebase-test3626',
    storageBucket: 'bis-firebase-test3626.appspot.com',
    iosBundleId: 'com.example.loginfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9LFDWFplr2DXaRfVjohQGke8xa2bOfmY',
    appId: '1:710171120768:ios:edbaa9066502e72e30c265',
    messagingSenderId: '710171120768',
    projectId: 'bis-firebase-test3626',
    storageBucket: 'bis-firebase-test3626.appspot.com',
    iosBundleId: 'com.example.loginfit.RunnerTests',
  );
}
